Ollama:
  Host: "http://localhost:11434"
  Model: "deepseek-r1:7b"
  Stream: false

CodeCheck:
  CheckDay: -2 # -1:yesterday 1:today
  #ProjectPath: "D:\\testollama"
  #RepoURL: "http://zt-c600540.ztgame.com/svn/testollama/"
  ProjectPath: "C:\\Users\\Meepo\\Desktop\\test"
  RepoURL: "https://desktop-ljl2un9/svn/test/"
  UserName: "test"
  Password: "test"
  DiffDir: "."
#  CodeCheckFormat: #return json response, just one issue
#    file: "string"
#    code: "string"
#    reason: "string"
#    fix: "string"
  Prompt:
    "请分析代码变更，只分析C++代码，使用json回答。

     file: 代码文件名，从代码变更的Index: 后寻找
     code: 有问题的代码片段
     reason: 为什么有问题
     fix: 修改建议
     如果有多个问题，用多个json对象返回。

     当前需分析的代码变更：
     {{.Content}}"
