Ollama:
  Host: "http://localhost:11434"
  Model: "deepseek-r1:7b"
  Stream: false

CodeCheck:
  CheckDay: 1 # -1:yesterday 1:today
  ProjectPath: "D:\\testollama"
  RepoURL: "http://zt-c600540.ztgame.com/svn/testollama/"
  UserName: "test"
  Password: "test"
  DiffDir: "."
  CodeCheckFormat:
    file: "string"
    code: "string"
    reason: "string"
    fix: "string"
  Prompt:
    "请分析代码变更，严格按以下格式返回问题条目，json值为中文，只分析C++代码，不要包含分析过程或其他内容：
     **file**：<文件完整路径>
     **code**：
     ```cpp
     <出错的代码片段>
     ```
     **reason**：<简明扼要说明问题本质，单行50字>
     **fix**：
     ```cpp
     <修改后的正确代码>
     ---
     **示例**：
     file：main.cpp
     code：
     ```cpp
     std::cout << \"error: invalid input\" << std::endl;
     ```
     reason：直接输出到控制台不利调试和日志管理
     fix：
     ```cpp
     logger.error(\"Invalid input detected\");
      ```
     ---
     当前需分析的代码变更：
     ```diff
     {{.Content}}
     ```"
