Ollama:
  Host: "http://localhost:11434"
  Model: "deepseek-r1:7b"
  Stream: false
  Parameters:
    temperature: 0.2
    num_ctx: 10000
    max_token: 8092
    seed: 0
    top_p: 0.5
    top_k: 30
    language: "c++"
    frequency_penalty: 0.2
    presence_penalty: 0.1


CodeCheck:
  CheckDay: -4 # -1:yesterday 1:today
  #ProjectPath: "D:\\testollama"
  #RepoURL: "http://zt-c600540.ztgame.com/svn/testollama/"
  ProjectPath: "C:\\Users\\Meepo\\Desktop\\test"
  RepoURL: "https://desktop-ljl2un9/svn/test/"
  UserName: "test"
  Password: "test"
  DiffDir: "."

  Prompt: |
    "
    ### 需要审查的代码变更内容：
    ```diff
    {{.Content}}
    ```
    你是一个资深C++代码审查专家，请严格按照以下格式要求回复，禁止回复其他内容：
    1. 仅分析.cpp/.h/.hpp文件
    2. 按文件逐个分析
    3. 每个文件按如下结构输出：
    [文件名] <实际文件名>
    [问题代码] 
    > 有问题的代码片段
    [修改建议]
    > 给出具体修改方案
    
    格式示例：
    [文件名] 文件名
    [问题代码]
    ```cpp
      有问题的代码
    ```
    [修改建议]
    修改建议
    "


#高严格性审查（安全关键代码）:
#  {"temperature": 0.0, "top_k": 30, "frequency_penalty": 0.5}
#探索性审查（寻找潜在优化点）:
#  {"temperature": 0.3, "top_p": 0.9, "presence_penalty": 0.5}
#超长diff处理（>4096 tokens）:
#  {"num_ctx": 6144, "max_tokens": 4096}  # 需确认模型版本支持