Ollama:
  Host: "http://localhost:11434"
  Model: "deepseek-r1:7b"
  Stream: false

CodeCheck:
  CheckDay: 1 # -1:yesterday 1:today
  ProjectPath: "D:\\testollama"
  RepoURL: "http://zt-c600540.ztgame.com/svn/testollama/"
  #ProjectPath: "C:\\Users\\Meepo\\Desktop\\test"
  #RepoURL: "https://desktop-ljl2un9/svn/test/"
  UserName: "test"
  Password: "test"
  DiffDir: "."

  Prompt: |
    "请你帮我检查代码变更，只分析C++代码，指出其中问题且给出修改意见，使用中文输出，无需总结：
  
    需要检查的diff内容：
    ```diff
    {{.Content}}
    ```"
